platform :ios, "5.0"
pod 'AFNetworking', '~> 1.1.0'
pod 'DCIntrospect', '~> 0.0.2'
pod 'RCLocationManager', '~> 0.1'
pod 'MPFlipViewController', '~> 0.0.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'
pod 'YRDropdownView', '~> 0.0.1'
pod 'Nimbus/AttributedLabel', '~> 1.0.0'
pod 'Nimbus/NetworkImage', '~> 1.0.0'
pod 'FlurrySDK', '~> 4.1.0'
pod 'Mixpanel', '~> 1.1.1'
pod 'OpenUDID', '~> 1.0.0'
pod 'TestFlightSDK', '~> 1.2.4.beta'
pod 'SVHTTPRequest', '~> 0.4'
